<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBxSbdG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBxSbdG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOBxSbdG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOBxSbdG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOBxSbdG\App_KernelDevDebugContainer([
    'container.build_hash' => 'OBxSbdG',
    'container.build_id' => '9948580e',
    'container.build_time' => 1682426552,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBxSbdG');
